apiVersion: apps/v1
kind: Deployment
metadata:
  name: consul
  namespace: consul
spec:
  replicas: 1
  selector:
    matchLabels:
      app: consul
  template:
    metadata:
      labels:
        app: consul
    spec:
      containers:
      - name: consul
        image: hashicorp/consul:latest
        ports:
        - containerPort: 8500 # UI
        - containerPort: 8600 # DNS
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "200m"
        volumeMounts:
        - name: consul-config
          mountPath: /consul/config/config.hcl
          subPath: config.hcl
      volumes:
      - name: consul-config
        configMap:
          name: consul-config
