apiVersion: v1
kind: ConfigMap
metadata:
  name: consul-config
  namespace: consul
data:
  config.hcl: |
    data_dir = "/consul/data"
    bind_addr = "0.0.0.0"
    client_addr = "0.0.0.0"

    ui_config {
      enabled = true
    }

    connect {
      enabled = true
    }

    acl {
      enabled = true
      default_policy = "deny"
      enable_token_persistence = true
    }

    performance {
      raft_multiplier = 1
    }

    retry_join = ["consul.default.svc.cluster.local"]
