apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: vault-secrets-provider
  namespace: default
spec:
  provider: vault
  parameters:
    roleName: "app-role"
    vaultAddress: "https://vault.default.svc.cluster.local:8200"
    objects: |
      - objectName: "db-creds"
        secretPath: "database/creds/app-role"
        secretKey: "password"