- name: Deploy Vault using Helm
  hosts: k8s
  tasks:
    - name: Ensure Helm is installed
      ansible.builtin.command:
        cmd: helm version
      register: helm_installed
      failed_when: helm_installed.rc != 0

    - name: Add HashiCorp Helm repository
      ansible.builtin.command:
        cmd: helm repo add hashicorp https://helm.releases.hashicorp.com
      when: helm_installed is succeeded

    - name: Update Helm repositories
      ansible.builtin.command:
        cmd: helm repo update

    - name: Deploy Vault
      ansible.builtin.command:
        cmd: >
          helm upgrade --install vault hashicorp/vault \
          --namespace {{ vault_namespace | default('vault') }} \
          --create-namespace \
          --values /tmp/vault-values.yaml

    - name: Wait for Vault pods to be ready
      ansible.builtin.wait_for:
        port: 8200
        host: "{{ inventory_hostname }}"
        delay: 10
        timeout: 300