version: "3.9"

services:
  vault:
    image: hashicorp/vault:latest
    container_name: vault
    environment:
      VAULT_ADDR: "http://127.0.0.1:8200"
    ports:
      - "8200:8200"
    cap_add:
      - IPC_LOCK
    volumes:
      - ./services/vault/config:/vault/config
      - ./services/vault/data:/vault/data
    command: server -config=/vault/config/vault.hcl

  django:
    build:
      context: ./django_fst
    container_name: django
    environment:
      DJANGO_SETTINGS_MODULE: core.settings.prod
    ports:
      - "8001:8000"
    volumes:
      - ./django_fst:/app

  fastapi:
    build:
      context: ./fst_on_demand
    container_name: fastapi
    ports:
      - "8002:8000"
    volumes:
      - ./fst_on_demand:/app
