version: '3.8'

services:
  web:
    build:
      context: .
    ports:
      - "8000:8000"
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/app/gcs_key.json
    volumes:
      - /home/beaver/Work/learn-2-learn/gsc_key.json:/app/gsc_key.json