version: '3.8'

services:
  web:
    build:
      context: .
    ports:
      - "8000:8000"
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/app/gsc_key.json
    volumes:
      - /home/szogun/Documents/work/gsc_key.json:/app/gsc_key.json
    depends_on:
      - redis

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
