apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: default
  name: vault-role
rules:
- apiGroups: [""]
  resources: ["configmaps", "secrets"]
  verbs: ["get", "list", "watch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: vault-role-binding
  namespace: default
subjects:
- kind: ServiceAccount
  name: vault
  namespace: default
roleRef:
  kind: Role
  name: vault-role
  apiGroup: rbac.authorization.k8s.io
