# Generated by Django 5.1.4 on 2024-12-21 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VaultKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='A unique name for the Vault key.', max_length=255, unique=True)),
                ('value', models.TextField(help_text='Wartosc klucza Vault.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Vault Key',
                'verbose_name_plural': 'Vault Keys',
                'permissions': [('can_add_to_vault', 'Can add keys to Vault'), ('can_read_from_vault', 'Can read keys from Vault'), ('can_delete_from_vault', 'Can delete keys from Vault')],
                'unique_together': {('name', 'value')},
            },
        ),
    ]
