---
# infrastructure/k8s/configmaps/kind-config.yaml
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
  - role: control-plane
    image: l2l-base
    extraPortMappings:
      - containerPort: 6443
        hostPort: 6443
        protocol: TCP
      - containerPort: 8200
        hostPort: 8200
        protocol: TCP
      - containerPort: 8500
        hostPort: 8500
        protocol: TCP
    labels:
      node-role.kubernetes.io/control-plane: "true"
    kubeadmConfigPatches:
      - |
        kind: InitConfiguration
        nodeRegistration:
          kubeletExtraArgs:
            node-labels: "node-role.kubernetes.io/control-plane=true"

  - role: worker
    image: l2l-base
    labels:
      node-role.kubernetes.io/worker: "true"
    kubeadmConfigPatches:
      - |
        kind: JoinConfiguration
        nodeRegistration:
          kubeletExtraArgs:
            node-labels: "node-role.kubernetes.io/worker=true,app=consul"

  - role: worker
    image: l2l-base
    labels:
      node-role.kubernetes.io/worker: "true"
    kubeadmConfigPatches:
      - |
        kind: JoinConfiguration
        nodeRegistration:
          kubeletExtraArgs:
            node-labels: "node-role.kubernetes.io/worker=true,app=vault"

networking:
  disableDefaultCNI: false
  podSubnet: "10.244.0.0/16"
  serviceSubnet: "10.96.0.0/12"
