---
- name: Install prerequisites
  ansible.builtin.package:
    name: 
      - jq
      - curl
    state: present

- name: Configure Consul Helm values
  ansible.builtin.template:
    src: consul-values.yaml.j2
    dest: /tmp/consul-values.yaml

- name: Deploy Consul using Helm
  ansible.builtin.command:
    cmd: >
      helm upgrade --install consul hashicorp/consul
      --namespace consul
      --create-namespace
      --values /tmp/consul-values.yaml

- name: Wait for Consul pods to be ready
  ansible.builtin.wait_for:
    port: 8501
    host: "{{ inventory_hostname }}"
    delay: 10
    timeout: 300

- name: Configure Consul connect
  ansible.builtin.command:
    cmd: consul connect envoy -bootstrap
  register: consul_connect
  changed_when: "'Bootstrap configuration' in consul_connect.stdout"
