- name: Deploy API services
  hosts: api
  tasks:
    - name: Apply Django deployment
      kubernetes.core.k8s:
        state: present
        definition: "{{ lookup('file', 'k8s/manifests/dj-deployment.yaml') }}"

    - name: Apply FastAPI deployment
      kubernetes.core.k8s:
        state: present
        definition: "{{ lookup('file', 'k8s/manifests/fa-deployment.yaml') }}"