- name: Manage application secrets
  hosts: all
  tasks:
    - name: Fetch secrets from Vault
      hashivault_read:
        url: "{{ vault_url }}"
        role_id: "{{ vault_role_id }}"
        secret_id: "{{ vault_secret_id }}"
        secret: "database/creds/app-role"
      register: db_creds

    - name: Store secrets in Kubernetes
      kubernetes.core.k8s:
        state: present
        definition: |
          apiVersion: v1
          kind: Secret
          metadata:
            name: db-secrets
            namespace: default
          data:
            username: "{{ db_creds.data.username | b64encode }}"
            password: "{{ db_creds.data.password | b64encode }}"