---
# ansible/local/build_and_deploy_nginx.yml
- name: Build Docker image and deploy NGINX
  hosts: localhost
  tasks:
    - name: Check if Docker is installed
      ansible.builtin.command: docker --version
      register: docker_check
      failed_when: docker_check.rc != 0
      changed_when: false
      tags:
        - ensure_docker

    - name: Ensure Docker Compose plugin is installed
      ansible.builtin.command: docker compose version
      register: docker_compose_check
      failed_when: docker_compose_check.rc != 0
      changed_when: false
      tags:
        - ensure_docker

    - name: Check if Docker image l2l-nginx exists
      community.docker.docker_image_info:
        name: l2l-nginx
      register: docker_image_check
      ignore_errors: true
      tags:
        - cleanup
        - check

    - name: Check for running containers using l2l-nginx image
      ansible.builtin.shell: docker ps -q --filter "ancestor=l2l-nginx"
      register: running_containers
      failed_when: false
      changed_when: running_containers.stdout != ""
      tags:
        - cleanup
        - check

    - name: Stop and remove containers using l2l-nginx image
      community.docker.docker_container:
        name: "{{ item }}"
        state: absent
      loop: "{{ running_containers.stdout_lines }}"
      when: running_containers.stdout_lines | length > 0
      tags:
        - cleanup

    - name: Remove existing Docker image l2l-nginx if it exists
      community.docker.docker_image:
        name: l2l-nginx
        tag: latest
        state: absent
      when: >-
        docker_image_check.images is defined and
        docker_image_check.images | length > 0
      tags:
        - cleanup


    - name: Verify SSL certificates exist
      ansible.builtin.stat:
        path: ../../certs/bot-bee.online.certificate.pem
      register: cert_check
      tags:
        - certificates
        - setup

    - name: Fail if SSL certificates are missing
      ansible.builtin.fail:
        msg: "SSL certificates not found in ../../certs/"
      when: not cert_check.stat.exists
      tags:
        - certificates
        - setup

    - name: Build Docker image for NGINX
      community.docker.docker_image:
        name: l2l-nginx
        source: build
        build:
          path: "{{ playbook_dir }}/../../services/nginx"
        tag: latest
      tags:
        - build_image

    - name: Run NGINX container
      community.docker.docker_container:
        name: l2l-nginx
        image: l2l-nginx:latest
        state: started
        restart_policy: always
        published_ports:
          - "8080:80"
          - "8443:443"
        volumes:
          - "../../certs:/etc/ssl/nginx:ro"
      tags:
        - deploy
        - container

    - name: Copy SSL certificates to the host
      ansible.builtin.copy:
        src: ../../certs/
        dest: /etc/ssl/nginx/
        owner: root
        group: root
        mode: "0644"
      become: true
      changed_when: false
      tags:
        - certificates
        - setup

    - name: Display Docker system info
      ansible.builtin.command: docker system info
      register: docker_info
      tags:
        - debug
