---
- name: Deploy Consul to Kubernetes
  hosts: k8s
  tasks:
    - name: Apply ConfigMap for Consul
      k8s:
        state: present
        definition: "{{ lookup('file', 'learn-2-learn/k8s/configmaps/consul-config.yaml') }}"
    
    - name: Apply Deployment for Consul
      k8s:
        state: present
        definition: "{{ lookup('file', 'learn-2-learn/k8s/manifests/consul-deploy.yaml') }}"
    
    - name: Apply Service for Consul
      k8s:
        state: present
        definition: "{{ lookup('file', 'learn-2-learn/k8s/manifests/consul-service.yaml') }}"
