- name: Login to Vault with AppRole
  hashivault_approle_login:
    url: "http://127.0.0.1:8200"
    role_id: "{{ vault_role_id }}"
    secret_id: "{{ vault_secret_id }}"
  register: vault_login

- name: Create Django secrets
  hashivault_write:
    secret: secret/django
    token: "{{ vault_login.auth.client_token }}"
    data:
      SECRET_KEY: "{{ django_secret_key }}"
      PSQL_DB_DEV: "{{ django_db_name }}"
      PSQL_USER_DEV: "{{ django_user }}"
      PSQL_PASSWORD_DEV: "{{ django_password }}"
