apiVersion: v1
kind: Service
metadata:
  name: consul
  namespace: consul
  labels:
    app: consul
spec:
  ports:
    - port: 8500
      targetPort: 8500
      name: http
    - port: 8600
      targetPort: 8600
      name: dns
  selector:
    app: consul
