---
- name: Install prerequisites
  ansible.builtin.package:
    name: 
      - unzip
      - curl
    state: present

- name: Configure Vault Helm values
  ansible.builtin.template:
    src: vault-values.yaml.j2
    dest: /tmp/vault-values.yaml

- name: Deploy Vault using Helm
  ansible.builtin.command:
    cmd: >
      helm upgrade --install vault hashicorp/vault
      --namespace vault
      --create-namespace
      --values /tmp/vault-values.yaml

- name: Wait for Vault pods to be ready
  ansible.builtin.wait_for:
    port: 8200
    host: "{{ inventory_hostname }}"
    delay: 10
    timeout: 300

- name: Initialize Vault (if necessary)
  ansible.builtin.command:
    cmd: vault operator init -key-shares=1 -key-threshold=1
  register: vault_init
  failed_when: "'Unseal Key 1' not in vault_init.stdout"

- name: Unseal Vault
  ansible.builtin.command:
    cmd: >
      vault operator unseal {{ vault_init.stdout_lines[1].split(': ')[1] }}
  when: "'Unseal Key 1' in vault_init.stdout"

- name: Enable Vault audit logging
  ansible.builtin.command:
    cmd: vault audit enable file file_path=/var/log/vault_audit.log
