apiVersion: apps/v1
kind: Deployment
metadata:
  name: consul
  namespace: consul
spec:
  replicas: 3
  selector:
    matchLabels:
      app: consul
  template:
    metadata:
      labels:
        app: consul
    spec:
      containers:
      - name: consul
        image: hashicorp/consul:latest
        ports:
        - containerPort: 8500
        env:
        - name: CONSUL_BIND_INTERFACE
          value: eth0
