apiVersion: apps/v1
kind: Deployment
metadata:
  name: vault
  namespace: vault
spec:
  replicas: 2
  selector:
    matchLabels:
      app: vault
  template:
    metadata:
      labels:
        app: vault
    spec:
      containers:
      - name: vault
        image: hashicorp/vault:latest
        ports:
        - containerPort: 8200
        env:
        - name: VAULT_LOCAL_CONFIG
          value: |
            ui = true
            listener "tcp" {
              address     = "0.0.0.0:8200"
              tls_disable = 1
            }
            storage "raft" {
              path    = "/vault/data"
            }
            api_addr = "http://0.0.0.0:8200"
