name: Deploy to Kubernetes

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Ansible
      uses: dawidd6/action-ansible-playbook@v2
      with:
        playbook: ansible/playbooks/deploy_k8s.yaml
        inventory: ansible/inventory/hosts.yaml

    - name: Apply Kubernetes manifests
      uses: azure/k8s-deploy@v3
      with:
        manifests: |
          k8s/manifests/django-deployment.yaml
          k8s/manifests/fastapi-deployment.yaml
          k8s/manifests/vault-secret.yaml
